export const MARKETING_PAGES = {
  "landlord-compliance-software": {
    title: "Landlord Compliance Software for England",
    description: "Track landlord compliance deadlines, certificates and reminders across unlimited properties with RentClock.",
    eyebrow: "Landlord compliance software · England",
    lead: "One clear deadline ledger for gas safety, EICRs, EPCs, deposits and selected Renters’ Rights duties — built for landlords with 1–10 properties.",
    points: [["Every property in one view", "See what is overdue, due soon or missing without opening a spreadsheet."], ["Useful reminders", "Email alerts at 60, 30, 14 and 7 days, on the deadline and while an item remains overdue."], ["Documents beside dates", "Keep the certificate with the property record instead of hunting through old email."], ["England-specific checklist", "Track core national duties while keeping local licensing and property-specific checks separate."]],
    guide: "/guides/landlord-compliance-checklist-2026",
  },
  "gas-safety-certificate-reminders": {
    title: "Gas Safety Certificate Reminders for Landlords",
    description: "Record each gas safety deadline and get landlord reminder emails before the annual renewal date.",
    eyebrow: "Annual gas safety reminders",
    lead: "Put every property’s gas safety renewal date in one ledger and get reminders before it lapses — including the two-month retained-deadline window.",
    points: [["Annual deadline tracking", "Record the current deadline, not a vague note that the check was done sometime last year."], ["Early-window planning", "See the point two calendar months before the deadline when an early check can usually retain the existing renewal date."], ["Persistent overdue alerts", "An overdue item stays in the daily reminder until you record the new date."], ["Certificate storage", "Keep the latest landlord gas safety record beside the deadline it supports."]],
    guide: "/guides/gas-safety-certificate-renewal-rules",
    tool: "/tools/gas-safety-renewal-calculator",
  },
  "eicr-reminders": {
    title: "EICR Reminders for Landlords",
    description: "Track EICR inspection dates, earlier report dates and remedial deadlines for rental properties in England.",
    eyebrow: "Electrical safety deadline tracking",
    lead: "Track the inspection date the report actually requires, attach the EICR and avoid treating five years as an automatic rule when the report says sooner.",
    points: [["Earlier dates supported", "Use the next-inspection date on the report where it is earlier than five years."], ["Remedial work visibility", "Keep the 28-day rule — or a shorter period stated in the report — visible as a separate action."], ["Per-property records", "Give every address its own EICR date and document."], ["Advance email reminders", "Get notice before the tracked inspection date becomes urgent."]],
    guide: "/guides/eicr-landlord-remedial-deadlines",
    tool: "/tools/eicr-next-inspection-calculator",
  },
  "landlord-document-storage": {
    title: "Landlord Compliance Document Storage",
    description: "Store landlord compliance certificates privately beside each property's deadlines in RentClock.",
    eyebrow: "Documents that make sense",
    lead: "Keep gas records, EICRs, EPCs and supporting files beside the property and deadline they belong to — privately, without a generic folder maze.",
    points: [["Property-first filing", "Open an address and see its dates and evidence together."], ["Private account access", "Customer documents are isolated to their account rather than shared publicly."], ["Renewal context", "A document sits beside the date it proves, so the next action is clear."], ["Unlimited properties", "The same £5.99 monthly plan covers the whole portfolio."]],
    guide: "/guides/landlord-compliance-checklist-2026",
  },
};
